#ifndef CONFIG_HEADER
#define CONFIG_HEADER

#define SENSOR_LIST_SIZE 0
#define SENSOR_PINS_SIZE 8
#define EFFECTOR_LIST_SIZE 0
#define EFFECTOR_PINS_SIZE 8

#define TIMER_COG_OFFSET_TICKS 20
#define TIMER_COG_SLOTS 2
#endif
